### ISSUE TITLE
Check existence of autoloader before require

### ISSUE THREAD

**Issue by schlessera** [fklein-lu/checker-cli#10]
When using the Composer autoloader, you should always check whether the autoloader file exists, before you `require` it.

The reason is that someone else might pull in your package as a dependency through Composer, together with several other packages. Composer will then create one central autoloader in the root of the project that pulled in the dependencies. This autoloader will contain the namespaces of all dependencies regrouped. Within the folders of the individual dependencies, no autoloader is created because of this.

So, always load the Composer autoloader like this:

```
if (file_exists(__DIR__ . '/vendor/autoload.php'))
{
   require_once __DIR__ . '/vendor/autoload.php';
}
```

**Comment by grappler** [comment]
fixed in https://github.com/fklein-lu/checker-cli/commit/6ac1d82f117d7186f82424802e69b9082adba905
