### ISSUE TITLE
Prefer stable Composer packages

### ISSUE THREAD

**Issue by schlessera** [fklein-lu/checker-cli#11]
If you add `"minimum-stability": "dev"` to your `composer.json`, it is highly recommended to add `"prefer-stable": true` as well, otherwise you're always getting the latest master branch from the git repositories, instead of stable releases.

**Comment by grappler** [comment]
Yea, I ended up doing  that in one of my PR's https://github.com/fklein-lu/checker-cli/commit/dfac21637839554c70d1ab93e17400c6642987ac
