### ISSUE TITLE
Convention is to have src as namespace root

### ISSUE THREAD

**Issue by schlessera** [fklein-lu/checker-cli#9]
The convention with OOP code and using Composer autoloading is to have the `src` folder be the namespace root. This means that `src` should only contain classes, interfaces and traits.

The file `src/Application.php` does not fit in there, and should be put in the root folder of the package. This is what you normally call a "bootstrap" file, and the convention is to have it in the root folder.

**Comment by grappler** [comment]
Fixed in https://github.com/fklein-lu/checker-cli/commit/6ac1d82f117d7186f82424802e69b9082adba905
